# Generated by Django 6.0.7 on 2026-07-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='section',
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='positions.position'),
            preserve_default=False,
        ),
    ]
