# Generated by Django 6.0.7 on 2026-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_candidate_class_name_remove_candidate_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
    ]
