# Generated by Django 6.0.7 on 2026-07-19 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0003_alter_vote_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_number', models.PositiveIntegerField(unique=True)),
                ('previous_hash', models.CharField(max_length=64)),
                ('current_hash', models.CharField(max_length=64, unique=True)),
                ('nonce', models.PositiveIntegerField(default=0)),
                ('merkle_root', models.CharField(max_length=64)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='voting.vote')),
            ],
            options={
                'ordering': ['block_number'],
            },
        ),
    ]
