# Generated by Django 6.0.7 on 2026-07-17 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_options_remove_candidate_election_and_more'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'candidate'), name='unique_vote_per_candidate'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='blockchain_hash',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
    ]
