# Generated by Django 6.0.7 on 2026-07-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-voted_at']},
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_candidate',
        ),
    ]
