# Generated by Django 6.0.7 on 2026-07-16 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0002_election_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('max_candidates', models.PositiveIntegerField(default=10)),
                ('max_votes_per_voter', models.PositiveIntegerField(default=1)),
                ('result_type', models.CharField(choices=[('SINGLE', 'Single Winner'), ('MULTIPLE', 'Multiple Winners')], default='SINGLE', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
