# Generated by Django 6.0.7 on 2026-07-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_alter_election_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('CORPORATE', 'Corporate'), ('ACADEMIC', 'Academic'), ('GOVERNMENT', 'Government'), ('SOCIETY', 'Society / Association'), ('NGO', 'NGO'), ('CLUB', 'Club'), ('OTHER', 'Other')], default='CORPORATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
