# Generated by Django 6.0.7 on 2026-07-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VOTE', 'Vote'), ('PUBLISH_RESULTS', 'Publish Results'), ('CAST_VOTE', 'Cast Vote'), ('DUPLICATE_VOTE_ATTEMPT', 'Duplicate Vote Attempt'), ('VOTE_REJECTED', 'Vote Rejected')], max_length=30),
        ),
    ]
