# Generated by Django 6.0.7 on 2026-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VOTE', 'Vote'), ('PUBLISH_RESULTS', 'Publish Results'), ('CAST_VOTE', 'Cast Vote'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('DUPLICATE_VOTE_ATTEMPT', 'Duplicate Vote Attempt'), ('VOTE_REJECTED', 'Vote Rejected'), ('BLOCK_CREATED', 'Blockchain Block Created'), ('VERIFY', 'Blockchain Verification')], max_length=30),
        ),
    ]
